apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysql
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Timesheet@123
            - name: MYSQL_DATABASE
              value: db_test
            - name: MYSQL_USER
              value: root
          args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
            - --explicit_defaults_for_timestamp=true
            - --lower_case_table_names=1
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: mysqldb-data