apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None