apiVersion: v1
kind: Service
metadata:
  name: adminer-front
  labels:
    app: adminer-front
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: adminer-front