apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-frontend
  labels:
    app: springboot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-frontend
  template:
    metadata:
      labels:
        app: springboot-frontend
    spec:
      containers:
        - name: springboot-frontend
          image: shakilsaddam/springboot-mysql
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-frontend-svc
  labels:
    name: springboot-frontend-svc
spec:
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8080
      nodePort: 30081
  selector:
    app: springboot-frontend